// Seed script to insert sample Indian internal/platform/external jobs
// Run with: node scripts/seedJobs.js

const connectDB = require('../config/db');
const Job = require('../models/Job');

const seedJobs = async () => {
  try {
    await connectDB();

    // Remove any old sample jobs by title tag or by known seed companies
    await Job.deleteMany({ $or: [{ 'title': /\[SAMPLE\]/i }, { company: { $in: ['Internshala', 'Unstop', 'Microsoft India', 'Amazon India', 'Google India', 'Campus Partner'] } }] });

    // New, realistic Indian jobs and internships (30 records) with required fields
    const jobs = [
      {
        title: 'Frontend Intern',
        company: 'Internshala',
        location: 'Remote, India',
        city: 'Remote India',
        type: 'Internship',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://internshala.com/internships',
        platform: 'Internshala',
        isVerified: true,
        salary: null,
        stipend: '8,000 - 12,000 INR/month',
        skills: ['React', 'JavaScript', 'CSS'],
        responsibilities: ['Build UI components', 'Work with designers', 'Fix bugs'],
        eligibility: 'B.Tech / B.Sc students (2nd/3rd year preferred)',
        perks: ['Certificate', 'Flexible hours'],
        description: 'Remote Frontend internship building components and learning modern frontend tooling.',
        postedAt: new Date()
      },
      {
        title: 'MERN Stack Intern',
        company: 'Unstop',
        location: 'Bangalore, India',
        city: 'Bangalore',
        type: 'Internship',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://unstop.com/',
        platform: 'Unstop',
        isVerified: true,
        stipend: '10,000 INR/month',
        skills: ['React', 'Node.js', 'MongoDB'],
        responsibilities: ['Implement features', 'Write tests', 'Collaborate with team'],
        eligibility: 'Open to 2nd/3rd year students',
        perks: ['Mentorship', 'Stipend'],
        description: 'Work on full-stack features and learn production workflows.',
        postedAt: new Date(Date.now() - 1*24*60*60*1000)
      },
      {
        title: 'Data Analyst Intern',
        company: 'Microsoft India',
        location: 'Hyderabad, India',
        city: 'Hyderabad',
        type: 'Internship',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://careers.microsoft.com/',
        platform: 'Microsoft',
        isVerified: true,
        stipend: '12,000 INR/month',
        skills: ['SQL', 'Excel', 'Power BI'],
        responsibilities: ['Analyze datasets', 'Prepare reports', 'Support product team'],
        eligibility: 'Students with basics of statistics',
        perks: ['Certificate', 'Learning resources'],
        description: 'Data Analyst internship focusing on analytics and reporting.',
        postedAt: new Date(Date.now() - 2*24*60*60*1000)
      },
      {
        title: 'Software Intern',
        company: 'Amazon India',
        location: 'Bangalore, India',
        city: 'Bangalore',
        type: 'Internship',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://www.amazon.jobs/en/',
        platform: 'Amazon',
        isVerified: true,
        stipend: '22,000 INR/month',
        skills: ['Java', 'Data Structures'],
        responsibilities: ['Implement services', 'Participate in review'],
        eligibility: 'Open to students',
        perks: ['Stipend', 'Networking'],
        description: 'Internship involving backend systems and scalable services.',
        postedAt: new Date(Date.now() - 3*24*60*60*1000)
      },
      {
        title: 'Web Developer Intern',
        company: 'Zoho',
        location: 'Chennai, India',
        city: 'Chennai',
        type: 'Internship',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://zoho.com/careers',
        platform: 'Zoho',
        isVerified: true,
        stipend: '9,000 INR/month',
        skills: ['HTML', 'CSS', 'JavaScript'],
        responsibilities: ['Build responsive pages', 'QA and bug fixes'],
        eligibility: 'Open to students',
        perks: ['Certificate'],
        description: 'Frontend web development internship at Zoho.',
        postedAt: new Date(Date.now() - 4*24*60*60*1000)
      },
      {
        title: 'Software Engineer (Fresher)',
        company: 'TCS',
        location: 'Pune, India',
        city: 'Pune',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://www.tcs.com/careers',
        platform: 'TCS',
        isVerified: true,
        salary: '3,00,000 - 4,50,000 INR/year',
        skills: ['Java', 'Problem Solving'],
        responsibilities: ['Develop applications', 'Participate in code reviews'],
        eligibility: 'Fresh graduates',
        perks: ['Health insurance', 'Training'],
        description: 'Entry-level software engineer role at TCS for fresh graduates.',
        postedAt: new Date(Date.now() - 5*24*60*60*1000)
      },
      {
        title: 'Full Stack Developer',
        company: 'Infosys',
        location: 'Bangalore, India',
        city: 'Bangalore',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://www.infosys.com/careers',
        platform: 'Infosys',
        isVerified: true,
        salary: '5,00,000 - 8,00,000 INR/year',
        skills: ['Node.js', 'React', 'SQL'],
        responsibilities: ['Implement features', 'Maintain services'],
        eligibility: '0-2 years experience',
        perks: ['Flexible hours', 'Health benefits'],
        description: 'Full stack role building enterprise software.',
        postedAt: new Date(Date.now() - 6*24*60*60*1000)
      },
      {
        title: 'Backend Engineer',
        company: 'Razorpay',
        location: 'Remote, India',
        city: 'Remote India',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://razorpay.com/careers',
        platform: 'Razorpay',
        isVerified: true,
        salary: '6,00,000 - 10,00,000 INR/year',
        skills: ['Node.js', 'Databases'],
        responsibilities: ['Design APIs', 'Ensure reliability'],
        eligibility: '1+ years experience',
        perks: ['Stock options', 'Health benefits'],
        description: 'Backend role focused on payments and APIs.',
        postedAt: new Date(Date.now() - 7*24*60*60*1000)
      },
      {
        title: 'Frontend Developer',
        company: 'Flipkart',
        location: 'Bangalore, India',
        city: 'Bangalore',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://www.flipkartcareers.com/',
        platform: 'Flipkart',
        isVerified: true,
        salary: '7,00,000 - 12,00,000 INR/year',
        skills: ['React', 'Performance'],
        responsibilities: ['Build performant UI', 'Optimize render paths'],
        eligibility: '1+ years experience',
        perks: ['Health insurance'],
        description: 'Frontend role at Flipkart.',
        postedAt: new Date(Date.now() - 8*24*60*60*1000)
      },
      {
        title: 'Associate Engineer',
        company: 'Wipro',
        location: 'Noida, India',
        city: 'Noida',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        applyUrl: 'https://careers.wipro.com/',
        platform: 'Wipro',
        isVerified: true,
        salary: '3,50,000 - 5,00,000 INR/year',
        skills: ['Java', 'SQL'],
        responsibilities: ['Support product development', 'Fix bugs'],
        eligibility: 'Freshers and early career',
        perks: ['Training', 'Health benefits'],
        description: 'Associate role for early career candidates.',
        postedAt: new Date(Date.now() - 9*24*60*60*1000)
      },
      {
        title: 'Frontend Developer (Campus)',
        company: 'Campus Partner',
        location: 'Pune, India',
        city: 'Pune',
        type: 'Job',
        jobType: 'Internal',
        applyType: 'internal',
        applyUrl: null,
        platform: null,
        isVerified: false,
        salary: '2,50,000 - 3,50,000 INR/year',
        skills: ['HTML', 'CSS', 'JavaScript'],
        responsibilities: ['Build UI', 'Work with mentors'],
        eligibility: 'Campus hires',
        perks: ['PPO opportunities', 'Mentorship'],
        description: 'Internal posting for a frontend developer.',
        postedAt: new Date(Date.now() - 10*24*60*60*1000)
      },
      {
        title: 'Junior Frontend Developer',
        company: 'EduTech Labs',
        location: 'Bangalore, India',
        city: 'Bangalore',
        type: 'Job',
        jobType: 'Internal',
        applyType: 'internal',
        applyUrl: null,
        platform: null,
        isVerified: true,
        salary: '3,00,000 - 4,50,000 INR/year',
        skills: ['React', 'Tailwind'],
        responsibilities: ['Build learning platform UI', 'Fix bugs'],
        eligibility: '0-2 years experience',
        perks: ['Flexible hours'],
        description: 'Build learning platform components for EduTech Labs.',
        postedAt: new Date(Date.now() - 11*24*60*60*1000)
      },
      {
        title: 'Backend Developer (Internship)',
        company: 'ByteWorks',
        location: 'Mumbai, India',
        city: 'Mumbai',
        type: 'Internship',
        jobType: 'Internal',
        applyType: 'internal',
        applyUrl: null,
        platform: null,
        isVerified: true,
        stipend: '11,000 INR/month',
        skills: ['Node.js', 'MongoDB'],
        responsibilities: ['API development', 'DB modeling'],
        eligibility: 'Computer Science students',
        perks: ['Certificate', 'Stipend'],
        description: 'Hands-on backend internship at ByteWorks.',
        postedAt: new Date(Date.now() - 12*24*60*60*1000)
      },
      {
        title: 'DevOps Intern',
        company: 'Horizon Labs',
        location: 'Hyderabad, India',
        city: 'Hyderabad',
        type: 'Internship',
        jobType: 'Internal',
        applyType: 'internal',
        platform: null,
        isVerified: true,
        stipend: '10,000 INR/month',
        skills: ['Linux', 'CI/CD', 'Docker'],
        responsibilities: ['Support CI/CD', 'Monitor deployments'],
        eligibility: 'Students with Linux basics',
        perks: ['Mentorship', 'Certificate'],
        description: 'Work on CI/CD pipelines and cloud deployments.',
        postedAt: new Date(Date.now() - 13*24*60*60*1000)
      },
      {
        title: 'MERN Stack Intern',
        company: 'NeoTech',
        location: 'Remote, India',
        city: 'Remote India',
        type: 'Internship',
        jobType: 'Internal',
        applyType: 'internal',
        isVerified: false,
        stipend: '9,000 INR/month',
        skills: ['MongoDB', 'Express', 'React', 'Node.js'],
        responsibilities: ['Feature implementation', 'Unit tests'],
        eligibility: 'Open to students',
        perks: ['Remote', 'Mentorship'],
        description: 'Remote MERN internship building end-to-end features.',
        postedAt: new Date(Date.now() - 14*24*60*60*1000)
      },
      {
        title: 'QA Engineer - Intern',
        company: 'AlphaSoft',
        location: 'Chennai, India',
        city: 'Chennai',
        type: 'Internship',
        jobType: 'Internal',
        applyType: 'internal',
        isVerified: false,
        stipend: '6,000 INR/month',
        skills: ['Testing', 'Selenium'],
        responsibilities: ['Write test cases', 'Automate tests'],
        eligibility: 'Open to students',
        perks: ['Certificate'],
        description: 'QA internship focusing on automated testing.',
        postedAt: new Date(Date.now() - 15*24*60*60*1000)
      },
      {
        title: 'Full Stack Developer (Entry)',
        company: 'Beta Systems',
        location: 'Noida, India',
        city: 'Noida',
        type: 'Job',
        jobType: 'Internal',
        applyType: 'internal',
        isVerified: true,
        salary: '4,50,000 - 6,00,000 INR/year',
        skills: ['React', 'Node.js'],
        responsibilities: ['Develop features', 'Collaborate with PMs'],
        eligibility: 'Graduates',
        perks: ['Health benefits'],
        description: 'Work on frontend and backend features in a small team.',
        postedAt: new Date(Date.now() - 16*24*60*60*1000)
      },
      {
        title: 'Data Science Intern',
        company: 'Gamma Solutions',
        location: 'Ahmedabad, India',
        city: 'Ahmedabad',
        type: 'Internship',
        jobType: 'Internal',
        applyType: 'internal',
        isVerified: false,
        stipend: '12,000 INR/month',
        skills: ['Python', 'Pandas'],
        responsibilities: ['Data cleaning', 'Modeling'],
        eligibility: 'Statistics or CS students',
        perks: ['Mentorship'],
        description: 'Data science internship working on pipelines and ML tasks.',
        postedAt: new Date(Date.now() - 17*24*60*60*1000)
      },
      {
        title: 'Associate Software Engineer',
        company: 'Campus Partner',
        location: 'Pune, India',
        city: 'Pune',
        type: 'Job',
        jobType: 'Internal',
        applyType: 'internal',
        isVerified: false,
        salary: '3,00,000 - 4,00,000 INR/year',
        skills: ['JavaScript', 'Node.js'],
        responsibilities: ['Feature development', 'Fix bugs'],
        eligibility: 'Campus hires',
        perks: ['Campus hiring benefits'],
        description: 'Associate role for campus hiring programs.',
        postedAt: new Date(Date.now() - 18*24*60*60*1000)
      },
      {
        title: 'Frontend Intern (Bootcamp)',
        company: 'DevSphere',
        location: 'Jaipur, India',
        city: 'Jaipur',
        type: 'Internship',
        jobType: 'Internal',
        applyType: 'internal',
        isVerified: false,
        stipend: '7,000 INR/month',
        skills: ['HTML', 'CSS', 'JavaScript'],
        responsibilities: ['Build small projects', 'Attend bootcamp sessions'],
        eligibility: 'Open to students',
        perks: ['Bootcamp completion certificate'],
        description: 'Intensive bootcamp-style internship for frontend developers.',
        postedAt: new Date(Date.now() - 19*24*60*60*1000)
      },
      {
        title: 'SDE Intern',
        company: 'Amazon India',
        location: 'Bangalore, India',
        city: 'Bangalore',
        type: 'Internship',
        jobType: 'Platform',
        applyType: 'external',
        platform: 'Amazon',
        applyUrl: 'https://www.amazon.jobs/en/',
        isVerified: true,
        stipend: '20,000 INR/month',
        skills: ['Java', 'Data Structures'],
        responsibilities: ['Work on distributed systems', 'Participate in design discussions'],
        eligibility: 'Students with strong CS fundamentals',
        perks: ['Stipend', 'Networking'],
        description: 'SDE internship at Amazon India for students.',
        postedAt: new Date(Date.now() - 20*24*60*60*1000)
      },
      {
        title: 'Software Engineer - New Grad',
        company: 'Microsoft India',
        location: 'Hyderabad, India',
        city: 'Hyderabad',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        platform: 'Microsoft',
        applyUrl: 'https://careers.microsoft.com/india/',
        isVerified: true,
        salary: '12,00,000 - 18,00,000 INR/year',
        skills: ['C#', '.NET'],
        responsibilities: ['Develop software', 'Collaborate across teams'],
        eligibility: 'Graduates and new grads',
        perks: ['Stock options', 'Health benefits'],
        description: 'New grad software engineer role at Microsoft India.',
        postedAt: new Date(Date.now() - 21*24*60*60*1000)
      },
      {
        title: 'Frontend Engineer',
        company: 'Google India',
        location: 'Mumbai, India',
        city: 'Mumbai',
        type: 'Job',
        jobType: 'Platform',
        applyType: 'external',
        platform: 'Google',
        applyUrl: 'https://careers.google.com/',
        isVerified: true,
        salary: '15,00,000 - 25,00,000 INR/year',
        skills: ['JavaScript', 'React'],
        responsibilities: ['Build web applications', 'Performance tuning'],
        eligibility: 'Experienced engineers',
        perks: ['Health benefits', 'Stock options'],
        description: 'Frontend engineer role at Google India.',
        postedAt: new Date(Date.now() - 22*24*60*60*1000)
      }
    ];

    // Upsert jobs by (title, company, city) to avoid duplicates and ensure idempotency
    let upserted = 0;
    for (const j of jobs) {
      const filter = { title: j.title, company: j.company, city: j.city };
      const update = { $setOnInsert: { ...j, postedAt: j.postedAt || new Date() } };
      const res = await Job.updateOne(filter, update, { upsert: true });
      if (res.upsertedCount && res.upsertedCount > 0) upserted += 1;
    }
    console.log('Jobs seeded / upserted:', upserted);
    return upserted;
  } catch (error) {
    console.error('Error seeding jobs:', error);
    throw error;
  }
};

// When run directly, perform seeding and exit
if (require.main === module) {
  seedJobs().then(() => process.exit(0)).catch(() => process.exit(1));
}

module.exports = seedJobs;
